#!/usr/bin/env bash

# update apt-get
apt-get update

# Install script for apt-add-repository
apt-get install software-properties-common

## Install ansible
apt-add-repository -y ppa:ansible/ansible
apt-get update -y
apt-get install -y curl git ansible

